# Generated by Django 6.1.1 on 2026-09-20 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('profiles', '0001_initial'),
	]

	operations = [
		migrations.CreateModel(
			name='Skill',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
					),
				),
				('name', models.CharField(max_length=50, unique=True)),
			],
		),
		migrations.AddField(
			model_name='profile',
			name='headline',
			field=models.CharField(blank=True, max_length=120),
		),
		migrations.AddField(
			model_name='profile',
			name='location',
			field=models.CharField(blank=True, max_length=100),
		),
		migrations.CreateModel(
			name='Education',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
					),
				),
				('school', models.CharField(blank=True, max_length=100)),
				('degree', models.CharField(blank=True, max_length=100)),
				('start_year', models.PositiveIntegerField()),
				('end_year', models.PositiveIntegerField(blank=True, null=True)),
				(
					'profile',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='education',
						to='profiles.profile',
					),
				),
			],
		),
		migrations.CreateModel(
			name='Experience',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
					),
				),
				('company', models.CharField(max_length=100)),
				('title', models.CharField(max_length=100)),
				('description', models.TextField(blank=True)),
				('start_date', models.DateField()),
				('end_date', models.DateField(blank=True, null=True)),
				(
					'profile',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='experience',
						to='profiles.profile',
					),
				),
			],
		),
		migrations.CreateModel(
			name='Link',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
					),
				),
				('label', models.CharField(max_length=50)),
				('url', models.URLField()),
				(
					'profile',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='links',
						to='profiles.profile',
					),
				),
			],
		),
		migrations.AddField(
			model_name='profile',
			name='skills',
			field=models.ManyToManyField(blank=True, to='profiles.skill'),
		),
	]
