# Generated by Django 6.1.1 on 2026-09-22 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		('jobs', '0001_initial'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='Application',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('date', models.DateTimeField(auto_now_add=True)),
				(
					'applicant_user',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
					),
				),
				(
					'job',
					models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
				),
			],
		),
	]
