# Generated by Django 6.1.1 on 2026-09-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Consideration'), (2, 'Rejected'), (3, 'First Round'), (4, 'Second Round'), (5, 'Offer Extended')], default=1),
        ),
    ]
