# Generated by Django 6.1.1 on 2026-09-22 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='Job',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('description', models.TextField(max_length=1024)),
				('annual_salary_in_cents', models.IntegerField()),
				(
					'recruiter',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
					),
				),
			],
		),
	]
