# Generated by Django 5.0 on 2026-09-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0002_skill_profile_headline_profile_location_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='profiles.skill'),
        ),
    ]
