# Generated by Django 6.1.1 on 2026-09-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0002_skill_profile_headline_profile_location_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='profiles.skill'),
        ),
    ]
