# Generated by Django 6.1.1 on 2026-09-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='company', max_length=40),
            preserve_default=False,
        ),
    ]
